apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-backend
  template:
    metadata:
      labels:
        app: pfe-backend
    spec:
      containers:
        - name: pfe-backend
          image: sayarimohamed/pfe-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20