
apiVersion: v1
kind: Service
metadata:
  name: pfe-backend
  namespace: default
spec:
  selector:
    app: pfe-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
