sonar.organization=moh1920
sonar.projectKey=moh1920_Projet_recrutement_Pfe_Frontend
sonar.projectName=Projet_recrutement_Pfe_Frontend
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
