services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sayari
      MONGO_INITDB_ROOT_PASSWORD: sayari
    networks:
      - mongodb_network

  keycloak:
    container_name: keycloak-EspritRecrutement
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    volumes:
      - ./themes:/opt/keycloak/themes
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - mongodb_network

  # ─── Jitsi corrigé ───────────────────────────────────────
  jitsi:
    image: jitsi/web:stable-9364
    container_name: jitsi-meet
    ports:
      - "8443:80"
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - PUBLIC_URL=http://localhost:8443
    networks:
      - mongodb_network



volumes:
  data:


networks:
  mongodb_network:
    driver: bridge