spring:
  application:
    name: PfeBackendProject

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME:sayarim558@gmail.com}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://sayari:sayari@cluster0.ux5ktew.mongodb.net/pfe_db?retryWrites=true&w=majority}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak-app.orangesand-21e6d03b.germanywestcentral.azurecontainerapps.io//realms/espritRecrutement}

server:
  port: ${SERVER_PORT:8020}

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: espritRecrutement

keycloak-admin:
  server-url: ${KEYCLOAK_ADMIN_URL:https://keycloak-app.orangesand-21e6d03b.germanywestcentral.azurecontainerapps.io/}
  realm: espritRecrutement
  username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  client-id: admin-cli

# ============ GEMINI AI ============
gemini:
  api:
    key: ${GEMINI_API_KEY:}
  model: ${GEMINI_MODEL:gemini-3-flash-preview}
  max-output-tokens: 1500
  temperature: 0.3

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dpvqw1nd4}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

# ============ MANAGEMENT / HEALTH ============
management:
  metrics:
    tags:
      application: pfe-backend
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

ai:
  matching:
    api:
      url: ${MATCHING_API_URL:https://sayaru-matchingpfe.hf.space}


google:
  credentials:
    base64: ${GOOGLE_CREDENTIALS_BASE64}
  sheets:
    id: 1jpdx5dTNzxN9yV4SxlVeLj8d_3z3eeEEe1Mok-6r488
    range: "'Feuille 3'!A:AF"

n8n:
  webhook:
    url: https://sayari1234.app.n8n.cloud/webhook-test/offre-recrutement
    connect-timeout: 10000
    read-timeout: 120000
linkedin:
  api:
    token: AQWZnfWwoMnL_aDttPqFljGSJWQf33nuVR-BUtu0ypz21dtuaKg2VuCajSdz2CSk4dlA8fT4J8gCx_yC2OPViiiAdsWyNePKAKhEZ8_XuGjwFY-zkwi2UCIrVHQCmf1jRSzSHzZrQEiyPZQn04D_1F97gDan1ql992SXv-DM7ikqWZ7QQ3U5j48eSOL7UsCrvUy4_k8HUrTnNQyR-G9chIvNcY09pKmGqjH7R8BfTs64UCKQZgmNkNTNRfv41OA51qA6uGywfW9YXEgAqsHKG3fL9zbPKDc6Eq5hdfp1M9yNBAFJGrfRRwMJ-Rfdfu6KrRwcJ_dIxP9zGoGN0GRcEy4kseEVNA
  person:
    urn: urn:li:person:bU-CvNRdj0


groq:
  api:
    key: ${GROQ_API_KEY}