spring:
  spring:
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
  application:
    name: PfeBackendProject
  mail:
    host: smtp.gmail.com
    port: 465
    username: sayarim558@gmail.com
    password: qejy ajpu qaof vfez
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp


  data:
    mongodb:
      authentication-database: admin
      username: sayari
      password: sayari
      database: pfe_db
      port: 27017
      host: localhost

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/espritRecrutement

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: espritRecrutement

keycloak-admin:
  server-url: http://localhost:9090
  realm: espritRecrutement
  username: admin
  password: admin
  client-id: admin-cli


  

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8020



# ============ GEMINI AI ============
gemini:
  api:
    key: ${GEMINI_API_KEY}
  model: gemini-3.5-flash
  max-output-tokens: 1500
  temperature: 0.3


cloudinary:
  cloud-name : dpvqw1nd4
  api-key : 842164992996356
  api-secret : _HsPSNcA3gw5INs6FVFxUp3pCsI

google:
  credentials:
    path: serene-segment-496522-j8-b3c2874910f0.json
  sheets:
    id: 1jpdx5dTNzxN9yV4SxlVeLj8d_3z3eeEEe1Mok-6r488
    range: "'Feuille 3'!A:AF"


n8n:
  webhook:
    url: https://sayari1234.app.n8n.cloud/webhook-test/offre-recrutement
    connect-timeout: 10000
    read-timeout: 120000


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: pfe-backend   # ← nom qui apparaît dans Grafana

ai:
  matching:
    api:
      url: ${MATCHING_API_URL:https://sayaru-matchingpfe.hf.space}


linkedin:
  api:
    token: AQWZnfWwoMnL_aDttPqFljGSJWQf33nuVR-BUtu0ypz21dtuaKg2VuCajSdz2CSk4dlA8fT4J8gCx_yC2OPViiiAdsWyNePKAKhEZ8_XuGjwFY-zkwi2UCIrVHQCmf1jRSzSHzZrQEiyPZQn04D_1F97gDan1ql992SXv-DM7ikqWZ7QQ3U5j48eSOL7UsCrvUy4_k8HUrTnNQyR-G9chIvNcY09pKmGqjH7R8BfTs64UCKQZgmNkNTNRfv41OA51qA6uGywfW9YXEgAqsHKG3fL9zbPKDc6Eq5hdfp1M9yNBAFJGrfRRwMJ-Rfdfu6KrRwcJ_dIxP9zGoGN0GRcEy4kseEVNA
  person:
    urn: urn:li:person:bU-CvNRdj0

groq:
  api:
    key: ${GROQ_API_KEY}