spring:
  application:
    name: PfeBackendProject
  mail:
    host: smtp.gmail.com
    port: 465
    username: sayarim558@gmail.com
    password: qejy ajpu qaof vfez
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp


  data:
    mongodb:
      authentication-database: admin
      username: sayari
      password: sayari
      database: pfe_db
      port: 27017
      host: localhost

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/espritRecrutement

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: espritRecrutement

keycloak-admin:
  server-url: http://localhost:9090
  realm: espritRecrutement
  username: admin
  password: admin
  client-id: admin-cli


  

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8020
