spring:
  application:
    name: PfeBackendProject

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: smtp.gmail.com
    port: 465
    username: sayarim558@gmail.com
    password: qejy ajpu qaof vfez
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true

  data:
    mongodb:
      uri: mongodb://sayari:sayari@mongodb:27017/pfe_db?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/espritRecrutement

server:
  port: 8020

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: espritRecrutement

keycloak-admin:
  server-url: http://keycloak:9090
  realm: espritRecrutement
  username: admin
  password: admin
  client-id: admin-cli

# ============ GEMINI AI ============
gemini:
  api:
    key: AIzaSyAg1rmWQeguJfxl8vPJiUa5CVesfX4CPPU
  model: gemini-3-flash-preview
  max-output-tokens: 1500
  temperature: 0.3

cloudinary:
  cloud-name: dpvqw1nd4
  api-key: 842164992996356
  api-secret: _HsPSNcA3gw5INs6FVFxUp3pCsI


ai:
  matching:
    api:
      url: http://127.0.0.1:8001