apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: pfe-backend
        static_configs:
          - targets:
              - pfe-backend:80
        metrics_path: /actuator/prometheus